* starnursery.com
get app (why?)
15 reviews (no content) most 4 stars

* apps
- star nursery garden centers
- calendar app - what to do when in Nevada
"the gardener's calendar" - search for it online

learn about irrigation

house calls available 


* astro turf
it's nailed to the ground!

** maintenance
sweep with a brake or (steel?) broom
brush some kind of green silica sand on it?
every 6 - 8 months
*** TODO learn more about astroturf maintenance


* irrigation
plants & trees - twice a week right now!!
(how many minutes??)

mulch can hold moisture

water in the am, not night
(what about the evening??)

breaks up watering, especially during the summer

recommends a surge protector
the battery only stores the time of day
programming "embedded" into device
(lithium) battery lasts for about 5 years

* driphead types
red 2
black 1
blue 1/2
gallons / hour

35 m, stop 1 hour, then 25 minutes

the card from the city is for grass

at least 2 dripheads per plant

3 times max in the summer
30 minutes each, twice (about 30 - 60 minutes apart)

4 dripheads per tree would be better

move water away from trunk

control water volume by swapping dripheads

* valves
valves are not maintenance free!

need waterproof connector

might last only 2-3 years

** TODO check valves before summer!

diaphram might need replacing

outside water shutoff usually located outside (anti-siphon valve)
you don't have to shut it off from the sidewalk

sometimes there's a shutoff by the valve itself

Y filter - flush it twice a year - remove cap, turn on valve and count to 5
maybe around the time change?

there's a line with a cap that also needs to be flushed
don't bury under rocks

** DONE move rocks away from tree trunk
too much heat, trees can't breathe
add mulch around it!!

* landscapers
"know who you're hiring"

if rocks go up to the plants, how do you fertilize them??

Hugo at Eastern - Tu W Th opening - 11

"preventer" herbicides
can use after you kill them 
don't use when it's hot - follow instructions!!

check star notes for the right watering amounts

align the dripheads with the edge of the canopy of the shrub or tree

